/**
 * Intersect searchable universe with codes that have enough financials
 * for a valuability badge (full | structure_only) without runtime warm.
 *
 * Writes:
 *   public/data/universe_valuable.json  — rich subset (+ meta)
 *   src/data/valuableUniverse.js        — sync Set of codes for search badges
 *
 * Usage: node scripts/build_valuable_universe.mjs
 * npm:   npm run build:valuable-universe
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { STOCK_FINANCIALS } from '../src/data/stock_financials.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')
const universePath = path.join(root, 'public', 'data', 'universe.json')
const outJson = path.join(root, 'public', 'data', 'universe_valuable.json')
const outJs = path.join(root, 'src', 'data', 'valuableUniverse.js')

/** Mirror of src/data/loader.js assessValuability — keep in sync. */
function assessValuability(fin) {
  if (!fin || typeof fin !== 'object') return 'search_only'
  const price = Number(fin.price) || 0
  const eps = Number(fin.eps) || Number(fin.epsReported) || 0
  const bvps = Number(fin.bvps) || 0
  const pe = fin.pe_ttm != null && Number.isFinite(Number(fin.pe_ttm)) ? Number(fin.pe_ttm) : null
  const hasCore = eps !== 0 || bvps > 0 || (pe != null && pe !== 0)
  if (!hasCore && !(price > 0)) return 'search_only'
  if (!hasCore) return 'search_only'
  const hasCash =
    Number(fin.fcfPerShare) > 0 ||
    Number(fin.ownerEarnings) > 0 ||
    Number(fin.ocf) > 0 ||
    Number(fin.fcf) > 0
  const hasQuality = Number(fin.roe) > 0 && bvps > 0
  if (!hasCash && !hasQuality && !(eps !== 0 && pe != null)) return 'structure_only'
  if (!(price > 0) && !(eps !== 0 || bvps > 0)) return 'structure_only'
  return 'full'
}

function main() {
  if (!fs.existsSync(universePath)) {
    console.error('Missing public/data/universe.json — run npm run build:universe first')
    process.exit(1)
  }

  const universe = JSON.parse(fs.readFileSync(universePath, 'utf8'))
  if (!Array.isArray(universe)) {
    console.error('universe.json must be an array of { code, name, market }')
    process.exit(1)
  }

  const byCode = new Map(universe.map((u) => [String(u.code), u]))
  const valuable = []
  let full = 0
  let structureOnly = 0
  let finOnly = 0

  for (const [code, fin] of Object.entries(STOCK_FINANCIALS || {})) {
    const tier = assessValuability(fin)
    if (tier !== 'full' && tier !== 'structure_only') continue
    if (tier === 'full') full++
    else structureOnly++

    const row = byCode.get(String(code))
    if (row) {
      valuable.push({
        code: row.code,
        name: row.name,
        market: row.market,
        valuability: 'valuable',
        valuabilityTier: tier,
      })
    } else {
      finOnly++
      const market =
        String(code).length <= 5 ? 'HK' : String(code).startsWith('6') || String(code).startsWith('9') ? 'SH' : 'SZ'
      valuable.push({
        code: String(code),
        name: String(code),
        market,
        valuability: 'valuable',
        valuabilityTier: tier,
        outsideUniverse: true,
      })
    }
  }

  valuable.sort((a, b) => String(a.code).localeCompare(String(b.code)))
  const codes = valuable.map((v) => String(v.code))

  const payload = {
    asOf: new Date().toISOString().slice(0, 10),
    source: 'stock_financials ∩ universe',
    counts: {
      universe: universe.length,
      financials: Object.keys(STOCK_FINANCIALS || {}).length,
      valuable: valuable.length,
      full,
      structure_only: structureOnly,
      financialsOutsideUniverse: finOnly,
    },
    codes,
    items: valuable,
  }

  fs.mkdirSync(path.dirname(outJson), { recursive: true })
  fs.writeFileSync(outJson, JSON.stringify(payload))

  const js = `/**
 * Auto-generated by scripts/build_valuable_universe.mjs — do not edit by hand.
 * Codes with enough financials for 「可估值」search badges (no runtime warm required).
 * asOf: ${payload.asOf} · count: ${codes.length}
 */
export const VALUABLE_UNIVERSE_ASOF = ${JSON.stringify(payload.asOf)}
export const VALUABLE_CODES = new Set(${JSON.stringify(codes)})

export function isValuableCode(code) {
  return VALUABLE_CODES.has(String(code || ''))
}
`
  fs.writeFileSync(outJs, js)

  console.log(`Wrote ${valuable.length} valuable codes → universe_valuable.json + valuableUniverse.js`)
  console.log(
    `  universe ${universe.length} · financials ${payload.counts.financials} · full ${full} · structure_only ${structureOnly} · outsideUniverse ${finOnly}`,
  )
  if (valuable.length < 100) {
    console.warn('WARNING: valuable universe looks thin — check stock_financials.js')
    process.exitCode = 2
  }
}

main()
