#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — FinDigest China auth: domain + Supabase + Aliyun SMS/Mail
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

banner "FinDigest 国内登录开通（Supabase + 阿里云）"

stage "买国内域名（百度 / 备案前提）"
say "没有已备案域名，邮件推送和短信签名很难过审，百度也收不到。"
open_url "https://wanwang.aliyun.com/"
step "在阿里云万网选购一个域名（.com / .cn 均可）。"
step "完成实名认证。ICP 备案稍后再做（域名持有人与备案主体一致）。"
warn "这一步可以只下单域名；没有域名也能先配 Supabase，但邮件/短信会卡在审核。"
pause "域名已买好或暂时跳过，按 Enter"

stage "创建 Supabase 项目"
say "Supabase 当账号后端（可选后续全量 Auth）；国内访问多数时候可用。"
open_url "https://supabase.com/dashboard"
step "New project → 选一个离你近的区域（如 Northeast Asia / Singapore）。"
step "Project Settings → API → 复制 Project URL 与 anon public key。"
ask VITE_SUPABASE_URL "Paste Project URL (https://xxxx.supabase.co):"
ask VITE_SUPABASE_ANON_KEY "Paste anon public key:"
write_env VITE_SUPABASE_URL "$VITE_SUPABASE_URL"
write_env VITE_SUPABASE_ANON_KEY "$VITE_SUPABASE_ANON_KEY"
note "service_role key 只放 Edge Function / 服务器，不要写进前端。"

stage "阿里云 AccessKey"
say "用于短信 Dysmsapi + 邮件推送 DirectMail。"
open_url "https://ram.console.aliyun.com/manage/ak"
step "建议新建 RAM 用户，只开 dysms / dm 权限，再创建 AccessKey。"
warn "不要用主账号 AK 长期挂生产；也不要把 Secret 提交到 git。"
ask ALIYUN_ACCESS_KEY_ID "Paste AccessKey ID:"
ask_secret ALIYUN_ACCESS_KEY_SECRET "Paste AccessKey Secret:"
write_env ALIYUN_ACCESS_KEY_ID "$ALIYUN_ACCESS_KEY_ID"
write_env ALIYUN_ACCESS_KEY_SECRET "$ALIYUN_ACCESS_KEY_SECRET"

stage "阿里云短信（手机验证码）"
say "个人实名经常审不过签名；企业主体更容易。模板变量名必须是 code。"
open_url "https://dysms.console.aliyun.com/domestic/text/sign"
step "申请短信签名（建议与站点名一致，如 FinDigest）。"
step "申请模板，内容示例：您的验证码为 \${code}，10分钟内有效。"
warn "签名/模板「审核中」时，本地仍可用开发码；审核通过后才会真发短信。"
ask ALIYUN_SMS_SIGN_NAME "短信签名（SignName，审核通过后的中文名）:"
ask ALIYUN_SMS_TEMPLATE_CODE "模板 CODE（如 SMS_123456789）:"
write_env ALIYUN_SMS_SIGN_NAME "$ALIYUN_SMS_SIGN_NAME"
write_env ALIYUN_SMS_TEMPLATE_CODE "$ALIYUN_SMS_TEMPLATE_CODE"

stage "阿里云邮件推送（QQ / 163）"
say "必须把发信域名加到邮件推送并完成 DNS 验证。"
open_url "https://dm.console.aliyun.com/"
step "添加发信域名（建议 mail.你的域名.com 子域）。"
step "按控制台提示加 SPF / DKIM / MX 到域名 DNS，等到「验证通过」。"
step "创建发信地址，例如 noreply@mail.你的域名.com。"
ask ALIYUN_DM_ACCOUNT_NAME "发信地址 AccountName（完整邮箱）:"
ask ALIYUN_DM_FROM_ALIAS "发件人显示名 [默认 FinDigest]:"
[[ -z "${ALIYUN_DM_FROM_ALIAS:-}" ]] && ALIYUN_DM_FROM_ALIAS="FinDigest"
write_env ALIYUN_DM_ACCOUNT_NAME "$ALIYUN_DM_ACCOUNT_NAME"
write_env ALIYUN_DM_FROM_ALIAS "$ALIYUN_DM_FROM_ALIAS"

stage "OTP 密钥"
OTP_SECRET=$(openssl rand -hex 24 2>/dev/null || python -c "import secrets;print(secrets.token_hex(24))")
say "生成本地 EMAIL_OTP_SECRET（也可自己贴一个长随机串）。"
ask EMAIL_OTP_SECRET "EMAIL_OTP_SECRET [Enter 用刚生成的]:"
[[ -z "${EMAIL_OTP_SECRET:-}" ]] && EMAIL_OTP_SECRET="$OTP_SECRET"
write_env EMAIL_OTP_SECRET "$EMAIL_OTP_SECRET"

stage "Vercel 生产环境变量"
say "线上要真正发码，必须把同一套变量贴到 Vercel → Project → Settings → Environment Variables。"
open_url "https://vercel.com/dashboard"
step "为 Production（以及 Preview 如需要）添加："
note "  ALIYUN_ACCESS_KEY_ID / ALIYUN_ACCESS_KEY_SECRET"
note "  ALIYUN_SMS_SIGN_NAME / ALIYUN_SMS_TEMPLATE_CODE"
note "  ALIYUN_DM_ACCOUNT_NAME / ALIYUN_DM_FROM_ALIAS"
note "  EMAIL_OTP_SECRET"
note "  VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY（若要用前端 Supabase 客户端）"
warn "改完 VITE_* 后需要重新 Deploy 一次才会进前端包。"
pause "Vercel 变量已保存（或稍后手动贴），按 Enter"

stage "Supabase Edge Hooks（可选，全量 Auth 时）"
say "当前 App 已走 /api/auth + 阿里云；若以后用 Supabase signInWithOtp，再部署："
note "  supabase/functions/send-sms"
note "  supabase/functions/send-email"
step "Dashboard → Authentication → Hooks → 填函数 URL + Hook Secret。"
step "supabase secrets set 写入阿里云与 Hook Secret。"
pause "知道即可，按 Enter 结束"

say "本地下一步：重启 Vite（npm run dev），打开 /auth 测邮箱/短信页。"
say "未配好阿里云时，localhost 仍会显示「本地开发验证码」。"
finish
